version: "3.7"

services:
  database:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build: ./backend
    ports:
      - 8080:80
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - 80:80
    volumes:
      - ./frontend:/app
