version: '3.8'

services:
 backend:
  build: ./backend
  ports:
  - 5000:5000
  volumes:
  - ./backend:/app
  environment:
   FLASK_ENV: dev
   FLASK_DEBUG: 1

 frontend:
  build: ./frontend
  ports:
  - 4200:4200
  volumes:
  - ./frontend:/app

 database:
  image: mysql
  ports:
  - 3306:3306
  environment:
  - MYSQL_ROOT_PASSWORD=p@ssw0rd1
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config:
